// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgMjz1cJsQ38BnnH4xlWx8usDX69T48qE',
    appId: '1:409202988600:web:1d13c94bfcf8fb130638cd',
    messagingSenderId: '409202988600',
    projectId: 'conectong',
    authDomain: 'conectong.firebaseapp.com',
    storageBucket: 'conectong.appspot.com',
    measurementId: 'G-KLH32ZB4VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW6baDxlNiToEU3fcvJ1EUm9ByN8AJlTk',
    appId: '1:409202988600:android:a295ea5c32c3cc480638cd',
    messagingSenderId: '409202988600',
    projectId: 'conectong',
    storageBucket: 'conectong.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIG1UCYl2d9KNIs0MzWnDdArIaNr1s5CY',
    appId: '1:409202988600:ios:b05931ad328bd2570638cd',
    messagingSenderId: '409202988600',
    projectId: 'conectong',
    storageBucket: 'conectong.appspot.com',
    iosBundleId: 'com.example.fluther',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIG1UCYl2d9KNIs0MzWnDdArIaNr1s5CY',
    appId: '1:409202988600:ios:b05931ad328bd2570638cd',
    messagingSenderId: '409202988600',
    projectId: 'conectong',
    storageBucket: 'conectong.appspot.com',
    iosBundleId: 'com.example.fluther',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgMjz1cJsQ38BnnH4xlWx8usDX69T48qE',
    appId: '1:409202988600:web:3e7b0f7f9fe40b300638cd',
    messagingSenderId: '409202988600',
    projectId: 'conectong',
    authDomain: 'conectong.firebaseapp.com',
    storageBucket: 'conectong.appspot.com',
    measurementId: 'G-Z8JZGFE2FK',
  );

}